name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  imix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd implants/imix && cargo build --verbose
    - name: Run tests
      run: cd implants/imix && cargo test --verbose
  eldritch:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd implants/eldritch && cargo build --verbose
    - name: Run tests
      run: cd implants/eldritch && cargo test --verbose